# Generated by Django 5.0 on 2024-01-08 08:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.TextField(default='tvm')),
                ('features', models.TextField(default='superb')),
                ('flats_1bhk', models.PositiveIntegerField(default=0)),
                ('flats_2bhk', models.PositiveIntegerField(default=0)),
                ('flats_3bhk', models.PositiveIntegerField(default=0)),
                ('flats_4bhk', models.PositiveIntegerField(default=0)),
                ('cost_1bhk', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_2bhk', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_3bhk', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_4bhk', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('unit_type', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK')], default='1BHK', max_length=5)),
                ('agreement_end_date', models.DateField(default=datetime.date.today)),
                ('monthly_rent_date', models.DateField(default=datetime.date.today)),
                ('rent_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='tenant_documents')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.property')),
            ],
        ),
        migrations.DeleteModel(
            name='get',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
